cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: /UploadDir
spring:
  application:
    name: javaSpringBootErudio2025
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/NomeDoBancoDeDados?useTimezone=true&serverTimezone=UTC
    username: root
    password: suaSenha
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB
  logging:
    level:
      # root: WARN
      br.com.erudio: DEBUG
  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true
